// Canonical list of all serviceable cities, sourced from
// torontoairportlimo.com/rates.aspx (the full city dropdown).
// Used so every website city is selectable even when a specific
// airport/vehicle rate is not published (the UI then shows "Contact us").
export const WEBSITE_CITIES: string[] = [
  "Acton",
  "Ajax",
  "Aldershot",
  "Alliston",
  "Alton",
  "Amherstburg",
  "Ancaster",
  "Angus",
  "Arthur",
  "Ashburn",
  "Aurora",
  "Ayr",
  "Ballantrae",
  "Barrie",
  "Beamsville",
  "Beaverton",
  "Beeton",
  "Belleville",
  "Binbrook",
  "Blenheim",
  "Bolton",
  "Bond Head",
  "Bowmanville",
  "Bracebridge",
  "Bradford",
  "Brampton",
  "Brantford",
  "Brighton",
  "Brockville",
  "Brooklin",
  "Brougham",
  "Buffalo Airport, New York",
  "Buffalo, New York",
  "Burford",
  "Burlington",
  "Buttonville",
  "CFB Borden",
  "CFB Trenton",
  "Caledon East",
  "Caledonia",
  "Cambridge",
  "Campbellville",
  "Carlisle",
  "Casino Rama",
  "Cayuga",
  "Cedar Mills",
  "Chatham-Kent",
  "Cheltenham",
  "Claremont",
  "Clarington",
  "Cobourg",
  "Collingwood",
  "Concord",
  "Cookstown",
  "Courtice",
  "Creemore",
  "Deerhurst",
  "Delhi",
  "Detroit",
  "Douglas Point",
  "Dundas",
  "Durham",
  "Elmira",
  "Elora",
  "Ennismore",
  "Erin",
  "Essex",
  "Etobicoke",
  "Fenelon Falls",
  "Fergus",
  "Flamboro Centre",
  "Flamborough",
  "Flesherton",
  "Fort Erie",
  "Freelton",
  "Galt",
  "Gananoque",
  "Georgetown",
  "Goderich",
  "Goodwood",
  "Gormley",
  "Grand Valley",
  "Gravenhurst",
  "Greater Napanee",
  "Grimsby",
  "Guelph",
  "Hagersville",
  "Hamilton",
  "Hanover",
  "Hayden",
  "Holland Landing",
  "Horseshoe Valley Resort (Barrie)",
  "Huntsville",
  "Ingersoll",
  "Inglewood",
  "Innisfil",
  "Jacksons Point",
  "Jarvis",
  "Jordan",
  "Kawartha Lakes",
  "Keswick",
  "Kettleby",
  "Kilbride",
  "Kimberley",
  "King City",
  "Kingston",
  "Kitchener",
  "Kleinburg",
  "Lakefield",
  "Leamington",
  "Lincoln",
  "Lindsay",
  "Listowel",
  "London",
  "Loretto",
  "Loyalist",
  "Maple",
  "Markham",
  "Midland",
  "Millgrove",
  "Milton",
  "Mississauga",
  "Mono (Hockley Valley Resort)",
  "Mono Mills",
  "Montreal, Quebec",
  "Mt. Hope",
  "New Tecumseth",
  "Newcastle",
  "Newmarket",
  "Niagara Falls",
  "Niagara Falls, New York",
  "Niagara-on-the-Lake",
  "Nobleton",
  "Norfolk",
  "Norval",
  "Oakville",
  "Orangeville",
  "Orillia",
  "Orono",
  "Oshawa",
  "Ottawa",
  "Owen Sound",
  "Palgrave",
  "Paris",
  "Parry Sound",
  "Peterborough",
  "Pickering",
  "Picton",
  "Port Carling",
  "Port Colborne",
  "Port Dover",
  "Port Hope",
  "Port Perry",
  "Richmond Hill",
  "Rockport",
  "Rockwood",
  "Scarborough",
  "Schomberg",
  "Scugog",
  "Sharon",
  "Shelburne",
  "St. Catharines",
  "St. George",
  "St. Jacobs",
  "St. Marys",
  "St. Thomas",
  "Stoney Creek",
  "Stouffville",
  "Stratford",
  "Strathroy",
  "Sutton",
  "Tecumseh",
  "Terra Cotta",
  "Thornhill",
  "Thorold",
  "Tilbury",
  "Toronto (Airport Area)",
  "Toronto (Beaches Area)",
  "Toronto (Danforth Area)",
  "Toronto (Davisville Area)",
  "Toronto (Downtown Area)",
  "Toronto (East York Area)",
  "Toronto (Etobicoke Area)",
  "Toronto (Leaside Area)",
  "Toronto (Midtown Area)",
  "Toronto (Moore Park Area)",
  "Toronto (North York Area)",
  "Toronto (Rosedale Area)",
  "Toronto (Scarborough Area)",
  "Toronto (Yorkville Area)",
  "Toronto Airport",
  "Tottenham",
  "Trenton",
  "Unionville",
  "Uxbridge",
  "Vaughan",
  "Victoria",
  "Wasaga Beach",
  "Waterdown",
  "Waterloo",
  "Welland",
  "Whitby",
  "Windsor",
  "Woodbridge",
  "Woodstock",
];
